title: Cork Software Crafters
description: >-
  This is the official website of the Cork Software Crafters Meetup group, hosting event history and updates.
theme: minima # You can replace 'minima' with any other Jekyll theme name.

# Social media links
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/Cork-Software-Crafters" }
    - { platform: x, user_url: "https://x.com/CorkSwCraft" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/groups/12085596" }
    - { platform: meetup, user_url: "https://www.meetup.com/cork-software-crafters" }
