title: Cork Software Crafters
description: >-
  This is the official website of the Cork Software Crafters Meetup group, hosting event history and updates.
theme: minima # You can replace 'minima' with any other Jekyll theme name.
